# CMake generated Testfile for 
# Source directory: /home/kreshnik/Thesis/HTD/htd/test/htd
# Build directory: /home/kreshnik/Thesis/HTD/htd/test/htd
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MinDegreeOrderingAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/MinDegreeOrderingAlgorithmTest")
add_test(VertexSelectionStrategyTest "/home/kreshnik/Thesis/HTD/htd/test/htd/VertexSelectionStrategyTest")
add_test(LabelCollectionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabelCollectionTest")
add_test(LabeledHypergraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabeledHypergraphTest")
add_test(SetCoverAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/SetCoverAlgorithmTest")
add_test(LabeledGraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabeledGraphTest")
add_test(MaximumCardinalitySearchOrderingAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/MaximumCardinalitySearchOrderingAlgorithmTest")
add_test(TreeDecompositionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/TreeDecompositionTest")
add_test(BucketEliminationTreeDecompositionAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/BucketEliminationTreeDecompositionAlgorithmTest")
add_test(LibraryInstanceTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LibraryInstanceTest")
add_test(HyperedgeTest "/home/kreshnik/Thesis/HTD/htd/test/htd/HyperedgeTest")
add_test(PathDecompositionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/PathDecompositionTest")
add_test(TreeTest "/home/kreshnik/Thesis/HTD/htd/test/htd/TreeTest")
add_test(ConnectedComponentAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/ConnectedComponentAlgorithmTest")
add_test(ManipulationOperationTest "/home/kreshnik/Thesis/HTD/htd/test/htd/ManipulationOperationTest")
add_test(FactoryTest "/home/kreshnik/Thesis/HTD/htd/test/htd/FactoryTest")
add_test(RandomOrderingAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/RandomOrderingAlgorithmTest")
add_test(GraphDecompositionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/GraphDecompositionTest")
add_test(PostProcessingPathDecompositionAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/PostProcessingPathDecompositionAlgorithmTest")
add_test(TreeDecompositionOptimizationTest "/home/kreshnik/Thesis/HTD/htd/test/htd/TreeDecompositionOptimizationTest")
add_test(LabeledDirectedGraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabeledDirectedGraphTest")
add_test(HypergraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/HypergraphTest")
add_test(BucketEliminationGraphDecompositionAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/BucketEliminationGraphDecompositionAlgorithmTest")
add_test(IteratorTest "/home/kreshnik/Thesis/HTD/htd/test/htd/IteratorTest")
add_test(LabeledMultiGraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabeledMultiGraphTest")
add_test(HypertreeDecompositionAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/HypertreeDecompositionAlgorithmTest")
add_test(MultiGraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/MultiGraphTest")
add_test(GraphLabelingTest "/home/kreshnik/Thesis/HTD/htd/test/htd/GraphLabelingTest")
add_test(FilteredHyperedgeCollectionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/FilteredHyperedgeCollectionTest")
add_test(GraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/GraphTest")
add_test(GraphPreprocessorTest "/home/kreshnik/Thesis/HTD/htd/test/htd/GraphPreprocessorTest")
add_test(HypertreeDecompositionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/HypertreeDecompositionTest")
add_test(LabelingCollectionTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabelingCollectionTest")
add_test(PathTest "/home/kreshnik/Thesis/HTD/htd/test/htd/PathTest")
add_test(MultiHypergraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/MultiHypergraphTest")
add_test(MinFillOrderingAlgorithmTest "/home/kreshnik/Thesis/HTD/htd/test/htd/MinFillOrderingAlgorithmTest")
add_test(HelperTest "/home/kreshnik/Thesis/HTD/htd/test/htd/HelperTest")
add_test(LabeledDirectedMultiGraphTest "/home/kreshnik/Thesis/HTD/htd/test/htd/LabeledDirectedMultiGraphTest")
